name: PHPCS check

on: pull_request

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing PHP
        uses: shivammathur/setup-php@2.4.2
        with:
          php-version: '7.4'
          coverage: none

      - name: Install composer dependencies
        run: |
          composer --no-interaction --no-progress --prefer-dist --dev install
      
      - name: Configure PHPCS for WordPress
        run: |
          ./vendor/bin/phpcs
